const itemList = [
  {
    item_id: 1,
    name: '현금케이크',
    detail: '돈 모양 케이크',
    delivery: '배달',
    kindOf: '레터링',
    color: '초록',
    flavor: '쑥',
    size: '2호',
    price: 12000,
    image_id: 11,
    imageLocate: '은평구',
    regDate: '2022.02.20',
    stock: 10,
    status: '품절',
    owner_id: 11,
    createdBy: '금쪽이네',
    store_Id: 324,
    storeName: '닷트',
    storeAddress: '서울 여기',
  },
  {
    item_id: 2,
    name: '딸기 케이크',
    detail: '딸기 가득 케이크',
    delivery: '픽업',
    kindOf: '레터링',
    color: '레드',
    flavor: '딸기',
    size: '1호',
    price: 500,
    image_id: 12,
    imageLocate: '/img/cake1.jpg',
    regDate: '2022.02.21',
    stock: 13,
    status: '재고 있음',
    owner_id: 12,
    createdBy: '딸기농장',
    store_Id: 12,
    storeName: '뮤르뮤르',
    storeAddress: '서울 종로구',
  },
  {
    item_id: 3,
    name: '애플케이크',
    detail: '한 입 베어먹은 애플 케이크',
    delivery: '배달',
    kindOf: '커스텀',
    color: '화이트',
    flavor: '사과',
    size: '3호',
    price: 900,
    image_id: 13,
    imageLocate: '/img/cake2.jpg',
    regDate: '2022.02.12',
    stock: 11,
    status: '재고 있음',
    owner_id: 13,
    createdBy: '',
    store_Id: 13,
    storeName: '닷트',
    storeAddress: '동작구',
  },
  {
    item_id: 4,
    name: '초코케이크',
    detail: '올인원 초코',
    delivery: '픽업',
    kindOf: '레터링',
    color: '블랙',
    flavor: '초코',
    size: '1호',
    price: 400,
    image_id: 14,
    imageLocate: '구리',
    regDate: '2022.02.10',
    stock: 15,
    status: '재고 있음',
    owner_id: 14,
    createdBy: '초코네',
    store_Id: 14,
    storeName: '닷트',
    storeAddress: '신촌',
  },
  {
    item_id: 5,
    name: '바나나케이크',
    detail: '12단 바나나케이크',
    delivery: '배달',
    kindOf: '레터링',
    color: '노랑',
    flavor: '바나나',
    size: '2호',
    price: 500,
    image_id: 15,
    imageLocate: '서오능',
    regDate: '2022.02.12',
    stock: 10,
    status: '재고 있음',
    owner_id: 55,
    createdBy: '호주 바나나농장',
    store_Id: 55,
    storeName: '닷트',
    storeAddress: '호주',
  },
];

export default itemList;
